---
title: "Home"
output:
  html_document:
    toc: false
---

The goal of this website is to explore the software used in weighted gene co-expression network analysis, [WGCNA](https://labs.genetics.ucla.edu/horvath/CoexpressionNetwork/). 

Briefly, the WGCNA software is designed to construct gene co-expression networks, that is, to find connections between multiple genes. In these networks, each gene is represented by a node, and the strength of the connection between nodes (genes) is based on gene expression level similarity. This similarity is usually measured by Pearson's correlation and then transformed. To read more about this transformation, or the mathematics behind gene co-expression networks, see the WGCNA theory papers [here](https://labs.genetics.ucla.edu/horvath/CoexpressionNetwork/). 

In addition to characterizing gene co-expression networks, there is also interest in integrating these networks with clinical data, such as weight. The goal of this process is identify potentially biologically meaningful groups of genes. By studying these groups of genes and, in particular, the key driver genes in each of these groups, one can develop genes of interest for these traits. These candidate genes could then be subjected to experimental validation as causal genes or evaluated for efficacy as biomarkers.

In the [first WGCNA tutorial in R](https://labs.genetics.ucla.edu/horvath/CoexpressionNetwork/Rpackages/WGCNA/Tutorials/), I analyzed a dataset of microarray-based gene expression measurements from 135 female mice. In addition to microarray data from each of the mice, there are also 25 body and metabolic-related traits, such as weight and glucose level. I am interested in identifying which genes/group of genes contribute most to each of these traits. For an overview of this process and a typical workflow, see [this short paper](https://labs.genetics.ucla.edu/horvath/CoexpressionNetwork/Rpackages/WGCNA/Tutorials/Simulated-00-Background.pdf). 

Below is code that I ran as part of tutorial 1. Most of the code was taken from the R scripts provided by the WGCNA authors, but most of the annotation outside of the code chunks is my own. 

* To see the data input and cleaning, click [here](https://lauren-blake.github.io/Explore_WGCNA/Tutorial_1.html).

* To see clustering based on the gene expression values of the mice, click [here](https://lauren-blake.github.io/Explore_WGCNA/Tutorial_1.html#sample_clustering).

* To see the clinical data collected on the mice, click [here](https://lauren-blake.github.io/Explore_WGCNA/Tutorial_1.html#add_the_clinical_data). 

* To see how a co-expression network is created, click [here](https://lauren-blake.github.io/Explore_WGCNA/Tutorial_1.html#gene_expression_network_construction_and_module_detection).

* To see the final clusters of highly interconnected genes ("modules"), click [here](https://lauren-blake.github.io/Explore_WGCNA/Tutorial_1.html#cluster_and_merge_modules_based_on_eigengenes).

* To see preliminary analysis between traits and the gene modules, click [here](https://lauren-blake.github.io/Explore_WGCNA/Tutorial_1.html#begin_to_study_relationships_between_traits_and_modules). Note: This topic is covered in greater depth in tutorials 2 and 3. 

* To look for enrichment, e.g. Gene Ontology terms, in the modules, click [here](https://lauren-blake.github.io/Explore_WGCNA/Tutorial_1.html#integrate_the_network_analysis_with_functional_enrichment).

* To see other plots created during this tutorial, click [here](https://lauren-blake.github.io/Explore_WGCNA/Tutorial_1.html#additional_visualizations).

Future plans: Complete the [second WGCNA tutorial](https://labs.genetics.ucla.edu/horvath/CoexpressionNetwork/Rpackages/WGCNA/Tutorials/). It covers comparing co-expression networks across 2 or more datasets, e.g. case-control, before-after treatment, etc. as well as further integrating these networks with other data. 

